# GNU Make solution makefile autogenerated by Premake
# Type "make help" for usage help

ifndef config
  config=release
endif
export config

PROJECTS := blink1_monitor

.PHONY: all clean help $(PROJECTS)

all: $(PROJECTS)

blink1_monitor: 
	@echo "==== Building blink1_monitor ($(config)) ===="
	@${MAKE} --no-print-directory -C . -f blink1_monitor.make

clean:
	@${MAKE} --no-print-directory -C . -f blink1_monitor.make clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "   release"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   blink1_monitor"
	@echo ""
	@echo "For more information, see http://industriousone.com/premake/quick-start"
